### ISSUE TITLE
It would be nice to be able to change the topic of the conversation 

### ISSUE THREAD

**Issue by ezrastoller** [cyrusstoller/EchoRemix#1]
I think there will be times when you want to change the topic of the conversation, but stay in a conversation with the same person (i.e. be able to change the topic of conversation without clicking "next conversation").

**Comment by cyrusstoller** [comment]
That's a good idea. I'll add a button under the `next conversation` button that's `next topic`. Or maybe it should be `new topic`? What do you think?
