### ISSUE TITLE
Add a timer

### ISSUE THREAD

**Issue by cyrusstoller** [cyrusstoller/EchoRemix#3]
Make it so that it's easier to keep track of how long a given conversation has lasted.

**Comment by sashenka87** [comment]
I had a bit of a hard time knowing the etiquette around ending a conversation.  What if you had a time set to a certain length (e.g., 2min or 5min) that then just gently "dinged" and participants could elect to re-up for another round or not.

**Comment by cyrusstoller** [comment]
I've added a timer to chat page. cc/ @megfitz
