### ISSUE TITLE
Audible ding for new message when the user is on a different tab

### ISSUE THREAD

**Issue by ezrastoller** [cyrusstoller/EchoRemix#4]
I really like how gchat has an audible ding for when a new message comes in, while you are in a different tab than your gchat. I think that would be great for echoremix, too.

**Comment by cyrusstoller** [comment]
Good suggestion. It's especially important when you're waiting to be matched with someone.

**Comment by cyrusstoller** [comment]
Need to make it so that the sound file is picked up by the asset pipeline.

**Comment by cyrusstoller** [comment]
Changed the directory to `/audios` because of the `ASSET_PUBLIC_DIRECTORIES` in https://github.com/rails/rails/blob/5b2ea20f562aa09ade8965f72c4075dd79609956/actionview/lib/action_view/helpers/asset_url_helper.rb and added the `mp3` file extension.
