### ISSUE TITLE
Name associated with system alerts

### ISSUE THREAD

**Issue by sashenka87** [cyrusstoller/EchoRemix#5]
This is a small issue but when you have "System" as the designator for instruction, that was really confusion and inhospitable.  It didn't feel very welcoming.

**Comment by cyrusstoller** [comment]
I guess this is why companies use names like Siri and Alexa. Any suggestions for what EchoRemix should use?

**Comment by cyrusstoller** [comment]
Didn't hear any complaints about this during the last beta test. I'm going to close this for now. Happy to revisit this in the future.
