### ISSUE TITLE
Show an error message when trying to open multiple tabs

### ISSUE THREAD

**Issue by cyrusstoller** [cyrusstoller/EchoRemix#6]
Keep people to a single tab.

If you open multiple tabs it will force you to exit from your first conversation, which is pretty annoying. Instead of trying to sync the tabs, while being conservative about destroying previous conversations, the site should detect the cookie and tell the user to go to the other window that's open.

cc/ @shafiquerashid

**Comment by cyrusstoller** [comment]
Unfortunately this is a little harder than I had expected. It's hard to differentiate between a valid page refresh and a user opening `/chat` in a new tab.

Doing something like:

```ruby
(REDIS.pubsub "numsub", "user_#{user_id}")[1]
```

returns 0 on the initial load and then 1 after the refresh. Essentially, a first-time refresh and a single new tab look very similar to the server. Subsequent new tabs get handled as expected, but it's the initial one that is probably most critical to handle.

I could be wrong on this, but my inclination is that the page reload functionality is more important than the inconvenience of being thrown out of a conversation when users open a new tab and try to go to the '/chat' route manually. @shafiquerashid and @ezrastoller what do you think?

**Comment by shafiquerashid** [comment]
@cyrusstoller agreed. Though I think you can actually detect refresh in browser using the `window.performance.navigation` object. `performance.navigation.type` returns 1 if the page is reloaded rather than navigated to via other means. 

So basically,only throw up an error message if `performance.navigation.type !== 1` and you are getting a ` (REDIS.pubsub "numsub", "user_#{user_id}")[1] > 0` from the server, I think. And of course, just fall back on existing behavior if the `window.performance` object does not exist (though seems to be supported across all modern browsers).

Documentation here: https://developer.mozilla.org/en-US/docs/Web/API/Navigation_timing_API

**Comment by cyrusstoller** [comment]
@shafiquerashid That's a good idea. Didn't realize that callback existed. I'll check it out.

**Comment by cyrusstoller** [comment]
I was able to get this technique to work for new connections. I check whether there are multiple connections and whether it's a refresh on the front-end and redirect to an error page if there's already an existing chat, but leave it so that the page refreshes as normal if it's the only page open.

The tricky part is that there's still a problem on disconnect. I don't think it's reliable to count on the front-end to send a message to the server on disconnect. I'm trying to figure out how to distinguish between when there's one page open that's being closed and a secondary page being open that's being closed. Both trigger same `#unsubscribe` action when the connection is terminated. It looks like `(REDIS.pubsub "numsub", user_id)[1]` returns `1` in both cases.

**Comment by cyrusstoller** [comment]
It might just be easier to treat each tab separately and take the risk that people could get matched with themselves.

**Comment by shafiquerashid** [comment]
Hmm interesting - just to clarify, is there a socket connection being created on the secondary tab before you redirect them to an error page?

**Comment by cyrusstoller** [comment]
Yup. Each page has a socket connection. I guess I could limit socket connections to only the chat page.

**Comment by shafiquerashid** [comment]
Yeah I think that makes sense 👍 Though your call on the ROI ... this probably not a frequent use case.

**Comment by cyrusstoller** [comment]
For the time being I'm just going to make it so that each tab has an independent websocket connection. If people who are tinkering end up getting paired with themselves, I think that's ok.

**Comment by shafiquerashid** [comment]
Cool! They should be able figure it out pretty quickly when they get matched with themselves anyways, and can move onto the next convo.
