### ISSUE TITLE
Change the ding noise

### ISSUE THREAD

**Issue by ezrastoller** [cyrusstoller/EchoRemix#7]
The ding noise to notify the user that a new message came in when EchoRemix is in a new window sounds a little funny to me. I'd respond better to a noise that sounds less synthetic.

**Comment by cyrusstoller** [comment]
Happy to change this. Can you help me find another open source `mp3` to use?

**Comment by cyrusstoller** [comment]
@yonasb Do you know any good places to find open source sound effects?

**Comment by cyrusstoller** [comment]
Going to table this for now. Haven't heard this come up in the last sessions.
